sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "6"
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
